[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "aiofiles>=25.1.0",
    "aiosqlite>=0.22.1",
    "bcrypt==3.2.0",
    "fastapi[standard]>=0.128.0",
    "passlib[argon2,bcrypt]>=1.7.4",
    "pydantic[all]>=2.12.5",
    "python-dotenv>=1.2.1",
    "python-jose[cryptography]>=3.5.0",
    "python-multipart>=0.0.22",
    "sqlalchemy[standard]>=2.0.46",
    "stripe>=14.4.0",
    "uvicorn>=0.40.0",
]
