import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { AuthProvider } from "../contexts/AuthContext";
import Navbar from "../components/navbar/Navbar";
import { CategoriesProvider } from "../contexts/CategoryContext";
import { ProductsProvider } from "@/contexts/ProductContext";
import { ReviewsProvider } from "@/contexts/ReviewContext";
import "../globals.css";
import ThemeProvider from "@/components/theme/ThemeProvider";
import { Toaster } from "sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <CategoriesProvider>
            <ProductsProvider>
              <ReviewsProvider>
                <ThemeProvider>
                  <Navbar />
                  <main className="container mx-auto px-4 py-8">
                    {children}
                  </main>
                  <Toaster
                    position="top-right"
                    richColors
                    closeButton
                    theme="system"
                    toastOptions={{
                      style: {
                        background: "var(--color-gray-800)",
                        color: "var(--color-gray-100)",
                        border: "1px solid var(--color-gray-700)",
                      },
                      className: "font-sans",
                      duration: 4000,
                    }}
                  />
                </ThemeProvider>
              </ReviewsProvider>
            </ProductsProvider>
          </CategoriesProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
